version: 2.1

jobs:
  test-install:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run:
          name: Inspect Node
          command: |
            which node
            node -v
            which npm
            npm -v
      - run:
          name: Check where NPM global installs
          command: |
            pwd
            npm list -g | head -1
            npm list -g --depth=0
            npm config get prefix
#       - run:
#           name: Set NPM global
#           command: |
#             mkdir ~/project/npm-global
#             npm config set prefix "~/project/npm-global"
#             echo "export PATH=~/project/npm-global/bin:$PATH" >> $BASH_ENV
#             echo "~/project/npm-global/bin/serverless@2.5.0" >> ci-npm-install-global.txt
#             npm config get prefix
      - restore_cache:
          key: npm-global-{{ .Branch }}
      - run:
          name: Check NPM config
          when: always
          command: |
            npm config get prefix
            npm list -g --depth=0
      - run:
          name: Check Serverless
          when: always
          command: |
            npx sls
            command -v sls
            command -v serverless
      - run:
          name: Install Serverless globally
          command: |
            if [ ! "$(command -v serverless)" ]; then
              npm install --global serverless@2.5.0
            else
              echo "Serverless Framework CLI @2.5.0 already installed globally"
            fi
      - save_cache:
          paths:
            - /opt/circleci/.nvm/versions/node/v16.13.2/lib/node_modules
          key: npm-global-{{ .Branch }}
      - run:
          name: Test
          command: |
            serverless --help
            npx sls --help
 
workflows:
  main:
    jobs:
      - test-install
